### ISSUE TITLE
fit standard errors?

### ISSUE THREAD

**Issue by joethorley** [bcgov/ssdca#25]
I tried to do again all the command to obtain HC5 and I realized I can’t have same number that showed by Joe and team.

```
> ssd_hc5(boron_dists)
    prop   est    se   lcl   ucl
   <dbl> <dbl> <dbl> <dbl> <dbl>
1 0.0500  1.25 0.726 0.623  3.19
```

**Comment by joethorley** [comment]
The problem is that bootstrap sampling to get the standard error or confidence intervals of the tail of a distribution is inherently noisy - in fact even with 10,000 bootstrap intervals the estimates are not repeatable at 3 significant figures...

```
> ssd_hc(boron_lnorm, nboot = 10000)
# A tibble: 1 x 5
  percent   est    se   lcl   ucl
    <int> <dbl> <dbl> <dbl> <dbl>
1       5  1.68 0.686 0.876  3.53
> ssd_hc(boron_lnorm, nboot = 10000)
# A tibble: 1 x 5
  percent   est    se   lcl   ucl
    <int> <dbl> <dbl> <dbl> <dbl>
1       5  1.68 0.696 0.878  3.56
```
@cschwarz-stat-sfu-ca do you have any thoughts?

**Comment by EmilieDouss** [comment]
Hi,

Here is a traduction of what Francois told me. Ok. He says that it could  indeed be due to a too small bootstrap size. It's an interesting hypothesis. Maybe we could try with 100,000 or 1,000,000 bootstraps intervals and verify if we still have the problem. He also said to me that, by the way, for a calculation as important as a guideline, we should increase bootstrap intervals size. Even if it will take more time to calculate. He already had this discussion with a statistician professor and the professor pointed out that the time is not so important if we have a better estimation. In fact, we keep guidelines for many years (and more).

**Comment by joethorley** [comment]
@EmilieDouss I'm running the code right now.... I'll report back when its finished.

**Comment by joethorley** [comment]
OK so 100,000 bootstrap intervals to get the confidence intervals at 1% to 99% in 1% increments based on model averaging of the 6 main distributions takes 5.6 hours on my relative fast machine

```
> start <- Sys.time()
> predict(boron_dists, nboot = 100000)
# A tibble: 99 x 5
   percent   est    se   lcl   ucl
     <int> <dbl> <dbl> <dbl> <dbl>
 1       1 0.304 0.340 0.126  1.08
 2       2 0.544 0.464 0.239  1.70
 3       3 0.780 0.564 0.356  2.24
 4       4 1.01  0.654 0.478  2.74
 5       5 1.25  0.738 0.605  3.22
 6       6 1.49  0.816 0.736  3.68
 7       7 1.73  0.892 0.872  4.14
 8       8 1.97  0.965 1.01   4.58
 9       9 2.21  1.04  1.16   5.02
10      10 2.46  1.11  1.30   5.45
# ... with 89 more rows
> end <- Sys.time()
> 
> start - end
Time difference of -5.606927 hours
```

I'll run again to see how much the values change

**Comment by joethorley** [comment]
The results are generally identical at three to four significant figures with 100,000 interactions (they are not with 10,000 iterations)
```
> predict(boron_dists, nboot = 100000)
# A tibble: 99 x 5
   percent   est    se   lcl   ucl
     <int> <dbl> <dbl> <dbl> <dbl>
 1       1 0.304 0.340 0.126  1.08
 2       2 0.544 0.463 0.238  1.70
 3       3 0.780 0.564 0.355  2.24
 4       4 1.01  0.654 0.478  2.74
 5       5 1.25  0.737 0.604  3.22
 6       6 1.49  0.816 0.735  3.69
 7       7 1.73  0.892 0.871  4.14
 8       8 1.97  0.965 1.01   4.58
 9       9 2.21  1.04  1.16   5.02
10      10 2.46  1.11  1.30   5.45
# ... with 89 more rows
> end <- Sys.time()
> 
> start - end
Time difference of -5.452981 hours
```

**Comment by joethorley** [comment]
done
